### ISSUE TITLE
Error running diabetes data-to-paper example

### ISSUE THREAD

**Issue by derekthirstrup** [Technion-Kishony-lab/data-to-paper#25]
Here is the traceback.  The code continues to fail at data exploration step.   It appears that a previous process is locking the test.pdf file. Run failed unexpectedly
data-to-paper failed due to an unexpected error.

---

[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\derek\\AppData\\Local\\Temp\\data_to_paper_temp_e9442e23-7aa3-4d85-8fe0-168ee6b09c53\\test.pdf'

**Comment by rkishony** [comment]
fixed 
Commit: bb607288ef7d1bab733a308a30e3136a2e294e7e

New version 1.1.2 is pushed to pypi. So you can just:
`pip install data-to-paper`

or if you already installed the older version then first `pip uininstall data-to-paper`

let us know if it works for you

**Comment by derekthirstrup** [comment]
I just tested the new 1.1.2 version but I get the same error message.  Let me know if there is anything else I should try to get past this issue.  Run failed unexpectedly
data-to-paper failed due to an unexpected error.

---

[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\derek\\AppData\\Local\\Temp\\data_to_paper_temp_958836fa-9274-4491-9486-40e1a118ac27\\test.pdf'
---

Please report the exception traceback from the console as a GitHub issue.

You can now:

1. CLOSE the app to terminate the run. 

2. RE-TRY by click the reset button of prior stages.
