### ISSUE TITLE
How to use another scholar api?

### ISSUE THREAD

**Issue by zez1998216** [Technion-Kishony-lab/data-to-paper#26]
What should I do to use another scholar api(like， Scholar-AI API) instead of Semantic Scholar API？Because I failed to request a Semantic Scholar API.

**Comment by TalIfargan** [comment]
Hi @zez1998216, Thank you for reaching out!

Currently, using a different API is not supported, but we appreciate the suggestion and are considering adding this feature in the future.

Regarding the Semantic Scholar API key, have you tried requesting it using [this](https://www.semanticscholar.org/product/api#api-key-form) form? You will need to fill out the form with the correct details. From my experience, the Semantic Scholar team is quite responsive and does their best to provide quick support.

Hopefully, you'll receive your API key soon. Keep us posted.

**Comment by zez1998216** [comment]
> Hi @zez1998216, Thank you for reaching out!
> 
> Currently, using a different API is not supported, but we appreciate the suggestion and are considering adding this feature in the future.
> 
> Regarding the Semantic Scholar API key, have you tried requesting it using [this](https://www.semanticscholar.org/product/api#api-key-form) form? You will need to fill out the form with the correct details. From my experience, the Semantic Scholar team is quite responsive and does their best to provide quick support.
> 
> Hopefully, you'll receive your API key soon. Keep us posted.

Thanks for your replay and this excellent work D2P! I will try to request the api again.
