### ISSUE TITLE
Missing watermark.pdf from Data Exploration step (version 1.1.5)

### ISSUE THREAD

**Issue by derekthirstrup** [Technion-Kishony-lab/data-to-paper#27]
Run failed unexpectedly
data-to-paper failed due to an unexpected error.

---

no such file: 'C:\Users\derek\anaconda3\envs\data-to-paper\lib\site-packages\data_to_paper\latex\watermark.pdf'
---

I was able to resolve this issue by copying the watermark.pdf from following github src folder into local conda env latex site-packages folder.  "https://github.com/Technion-Kishony-lab/data-to-paper/blob/main/src/data_to_paper/latex/watermark.pdf"

**Comment by rkishony** [comment]
thanks for feedback. fixed. 
Commit: 286f5e319c31ece4340b7ccc854ee7b6dd8b99ab
also now properly includes other resource files. 

You can re-install from pypi:

```
pip install data-to-paper --upgrade
```

and check `data-to-paper --version` "(should be 1.1.6 or higher)

let us know if it works better now

**Comment by derekthirstrup** [comment]
This bug is resolved in version 1.1.6.  Thanks for fixing the issue.

**Comment by derekthirstrup** [comment]
closed
