### ISSUE TITLE
Run failed unexpectedly

### ISSUE THREAD

**Issue by Tianxu-Jia** [Technion-Kishony-lab/data-to-paper#29]
Run failed unexpectedly
data-to-paper failed due to an unexpected error.

---

Code tries to create a forbidden file data-to-paper/src/data_to_paper/llm_created_scripts/script_to_run.py.
---

Please report the exception traceback from the console as a GitHub issue.

You can now:

1. CLOSE the app to terminate the run. 

2. RE-TRY by click the reset button of prior stages.

**Comment by rkishony** [comment]
thanks!
can you pls provide: 
- the full traceback (from the terminal)
- which OS
- which data-to-paper version are you using? did you pip install or clone?
