### ISSUE TITLE
Allow restarting a step from the App

### ISSUE THREAD

**Issue by rkishony** [Technion-Kishony-lab/data-to-paper#6]
Should have a button on the app "Restart Step" - taking you back tot he Mission prompt editing phase. 
We can also allow going back to earlier steps, invalidating all products from there.

**Comment by TalIfargan** [comment]
> if the openAI connection fails and we restart the app, we keep getting the same message (i.e.: Failed to get response from OpenAI after 5 attempts). Definitely the app is not trying again.

Hi @shuther,
First, welcome and thanks for trying data-to-paper!
The "issue" you have described is not related to the current issue.
To make things clear for us and for other users, can you please open a new issue, describing in detail what was the issue you have encountered including details about your OS, descriptions of what you have tried to solve the issue and relevant screenshots.
It will be very helpful to keep things organized and clear!

I will be happy to try and help you with everything there :)

**Comment by TalIfargan** [comment]
done, added in 4cb2c338eb48fc3623d83eea77b935fb2f2c25a1
