### ISSUE TITLE
set OPENAI_BASE_URL - openAI

### ISSUE THREAD

**Issue by shuther** [Technion-Kishony-lab/data-to-paper#9]
even with updating env.py, it seems the script doesn't want to use the set openai base url:
script used:

**Comment by TalIfargan** [comment]
Hi @shuther,

Can you please provide the full details of what you are trying to achieve, a bit more details about your machine (like what OS you are using) and what you have already tried?

**Comment by TalIfargan** [comment]
Thanks @shuther, for giving more details.

I have created a new branch (attached to this issue), that should support llama3 (as an example), hopefully it will also make it more clear how to generalize to other ollama/litellm models. Specifically, look at the commit c699eebe04870a787f18ed732da2cd227e8e21a1.

**Comment by CptJackieSparrow** [comment]
Is there a newer update to this? I feel like many things change on env file.
